In [ ]:
#Logistik Regression(Sınıflandırma)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('UCI_Credit_Card.csv')

In [4]:
df.head(3)

   ID  LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month
0   1    20000.0    2          2  ...       0.0       0.0       0.0                           1
1   2   120000.0    2          2  ...    1000.0       0.0    2000.0                           1
2   3    90000.0    2          2  ...    1000.0    1000.0    5000.0                           0

[3 rows x 25 columns]

In [5]:
#Id sütununu kaldırırız gereksiz feature
df.drop('ID',axis=1,inplace=True)

In [6]:
df.head(3)

   LIMIT_BAL  SEX  EDUCATION  MARRIAGE  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month
0    20000.0    2          2         1  ...       0.0       0.0       0.0                           1
1   120000.0    2          2         2  ...    1000.0       0.0    2000.0                           1
2    90000.0    2          2         2  ...    1000.0    1000.0    5000.0                           0

[3 rows x 24 columns]

In [7]:
y = df['default.payment.next.month']
x = df.drop('default.payment.next.month',axis=1)

In [8]:
df.shape

(30000, 24)

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.77,random_state=6)

In [10]:
log=LogisticRegression()
model=log.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [11]:
model.score(x_test,y_test)

0.7739130434782608

In [12]:
x

       LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6
0        20000.0    2          2         1   24  ...     689.0       0.0       0.0       0.0       0.0
1       120000.0    2          2         2   26  ...    1000.0    1000.0    1000.0       0.0    2000.0
2        90000.0    2          2         2   34  ...    1500.0    1000.0    1000.0    1000.0    5000.0
3        50000.0    2          2         1   37  ...    2019.0    1200.0    1100.0    1069.0    1000.0
4        50000.0    1          2         1   57  ...   36681.0   10000.0    9000.0     689.0     679.0
...          ...  ...        ...       ...  ...  ...       ...       ...       ...       ...       ...
29995   220000.0    1          3         1   39  ...   20000.0    5003.0    3047.0    5000.0    1000.0
29996   150000.0    1          3         2   43  ...    3526.0    8998.0     129.0       0.0       0.0
29997    30000.0    1          2         2   37  ...       0.0   22000.0    4200.0    2000.0    3100.0
29998    80000.0    1          3         1   41  ...    3409.0    1178.0    1926.0   52964.0    1804.0
29999    50000.0    1          2         1   46  ...    1800.0    1430.0    1000.0    1000.0    1000.0

[30000 rows x 23 columns]

In [13]:
x.iloc[1903]

LIMIT_BAL    310000.0
SEX               2.0
EDUCATION         1.0
MARRIAGE          2.0
AGE              32.0
PAY_0             0.0
PAY_2             0.0
PAY_3             0.0
PAY_4             0.0
PAY_5             0.0
PAY_6             0.0
BILL_AMT1     35064.0
BILL_AMT2     38195.0
BILL_AMT3     39233.0
BILL_AMT4     39577.0
BILL_AMT5     42996.0
BILL_AMT6     46319.0
PAY_AMT1       4000.0
PAY_AMT2       2000.0
PAY_AMT3       2000.0
PAY_AMT4       4000.0
PAY_AMT5       4000.0
PAY_AMT6       4000.0
Name: 1903, dtype: float64

In [17]:
denemex = np.array(x.iloc[1903])

In [18]:
model.predict([denemex])

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [19]:
y.iloc[1903]

0